const MobData = [
  {
    id: 1,
    name: "Alligator",
    size: "Large",
    location: "X: 17.6, Y: 24.1",
    weather: "Showers",
    time: ["00:00", "23:59"],
    image: "",
  },
  {
    id: 2,
    name: "Beachcomb",
    size: "Small",
    location: "X: 18.0, Y: 13.0",
    weather: "Rain",
    time: ["00:00", "23:59"],
    image: "",
  },
  {
    id: 3,
    name: "Gold Back",
    size: "Large",
    location: "X: 13.1, Y: 28.4",
    weather: "Rain",
    time: ["00:00", "23:59"],
    image: "",
  },
  {
    id: 4,
    name: "Glyptodon",
    size: "Medium",
    location: "X: 31.5, Y: 11.5",
    weather: "All",
    time: ["00:00", "03:00"],
    image: "",
  },
  {
    id: 5,
    name: "Island Billy",
    size: "Large",
    location: "X: 26.3, Y: 22.8",
    weather: "All",
    time: ["03:00", "06:00"],
    image: "",
  },
  {
    id: 6,
    name: "Lemur",
    size: "Small",
    location: "X: 21.0, Y: 26.4",
    weather: "All",
    time: ["06:00", "09:00"],
    image: "",
  },
  {
    id: 7,
    name: "Star Marmot",
    size: "Small",
    location: "X: 16.0, Y: 19.0",
    weather: "All",
    time: ["09:00", "12:00"],
    image: "",
  },
  {
    id: 8,
    name: "Apkallu of Paradise",
    size: "Small",
    location: "X: 18.8, Y: 11.9",
    weather: "All",
    time: ["12:00", "15:00"],
    image: "",
  },
  {
    id: 9,
    name: "Dodo of Paradise",
    size: "Medium",
    location: "X: 16.6, Y: 11.8",
    weather: "All",
    time: ["15:00", "18:00"],
    image: "",
  },
  {
    id: 10,
    name: "Island Stag",
    size: "Medium",
    location: "X: 20.4, Y: 20.1",
    weather: "All",
    time: ["18:00", "21:00"],
    image: "",
  },
  {
    id: 11,
    name: "Black Chocobo",
    size: "Medium",
    location: "X: 13.1, Y: 11.5",
    weather: "Clear Skies",
    time: ["00:00", "23:59"],
    image: "",
  },
  {
    id: 12,
    name: "Grand Buffalo",
    size: "Large",
    location: "X: 12.1, Y: 17.2",
    weather: "Cloudy",
    time: ["00:00", "23:59"],
    image: "",
  },
  {
    id: 13,
    name: "Ornery Karakul",
    size: "Small",
    location: "X: 21.6, Y: 23.1",
    weather: "Fair Skies",
    time: ["00:00", "23:59"],
    image: "",
  },
  {
    id: 14,
    name: "Twinklefleece",
    size: "Small",
    location: "X: 22.3, Y: 20.5",
    weather: "Fog",
    time: ["00:00", "23:59"],
    image: "",
  },
  {
    id: 15,
    name: "Yellow Coblyn",
    size: "Small",
    location: "X: 26.6, Y: 19.5",
    weather: "Fog",
    time: ["00:00", "23:59"],
    image: "",
  },
];

export default MobData;
